test: integration test Redis
cloudfoundry/csb-brokerpak-gcp pull request #372
Opened 2022-05-23 18:10 UTC by zucchinidev

### Checklist:

* ~~[ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~
* [x] Have you followed the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)?

2022-05-24 09:03 UTC, pivotal-marcela-campo requested changes

2022-05-24 10:40 UTC, zucchinidev commented on google-redis.yml
> +    enum:
Thank you very much, @pivotal-marcela-campo, then I will add these new regions:
* asia-south2 (Delhi)
* asia-southeast2 (Jakarta)
* australia-southeast2 (Melbourne)
* europe-central2 (Warsaw)
* northamerica-northeast2 (Toronto)
* southamerica-west1 (Santiago)
* us-west3 (Salt Lake City)
* us-west4 (Las Vegas)

2022-05-24 10:53 UTC, zucchinidev commented on integration-tests/redis_test.go
> +					HaveKeyWithValue("instance_id", ContainSubstring("pcf-sb-")),
Good catch. Thank you!!!

2022-05-24 10:53 UTC, zucchinidev commented on google-redis.yml
> +    enum:
Done!

2022-05-25 07:59 UTC, pivotal-marcela-campo approved these changes
Looks good! Thanks!

2022-05-25 08:49 UTC, merged